#!/bin/sh

# Pre-removal shell script for Debian package

SYSTEMD=/etc/systemd/system
SERVICE=jupyterlab.service

# Stop and disable JupyterLab service
if [ -f $SYSTEMD/$SERVICE ]; then
  systemctl is-active $SERVICE > /dev/null 2>&1 && sudo systemctl stop $SERVICE
  sudo systemctl disable $SERVICE
  sudo rm -fr $SYSTEMD/$SERVICE
fi

# Uninstall JupyterLab
sudo pip3 uninstall -y jupyterlab
